"""Generate a cpuidmask rules file for a CPU target from its recorded flags.

The target is a software-layer-scripts#311 reference: the -m options GCC
resolved -march=native into on that hardware. Every -mno-X becomes a CPUID bit
to clear. The bit is found through GCC's own tables, nothing written by hand:

  i386-isas.h   option "-mX"     -> FEATURE_X
  cpuinfo.h     FEATURE_X        -> register and bit_ name, under the CPUID
                                    leaf and subleaf last queried above it
  cpuid.h       bit_ name        -> bit mask

    python gen_profile.py GCC_SRC_DIR REFERENCE [--signature LEAF1_EAX]
                          [--vendor GenuineIntel|AuthenticAMD] > rules

GCC_SRC_DIR holds cpuid.h, i386-isas.h and cpuinfo.h of the GCC version the
reference was recorded with. Output lines:
  clear LEAF SUB REG MASK     # -mno-X
  replace LEAF SUB REG VALUE  # signature, vendor
and a trailer listing -mno- options with no CPUID bit (XCR0-gated, or not a
CPUID feature), which a mask cannot express.
"""
import argparse
import os
import re
import sys

REGS = {"eax": 0, "ebx": 1, "ecx": 2, "edx": 3}


def bit_masks(cpuid_h):
    masks = {}
    for m in re.finditer(r"#define\s+(bit_\w+)\s+\(\s*(\d+)u?\s*<<\s*(\d+)\s*\)", open(cpuid_h).read()):
        masks[m.group(1)] = int(m.group(2)) << int(m.group(3))
    return masks


def option_features(isas_h):
    opts = {}
    for m in re.finditer(r'ISA_NAMES_TABLE_ENTRY\s*\(\s*"[^"]*"\s*,\s*(FEATURE_\w+)\s*,\s*\w+\s*,\s*"(-m[\w.-]+)"',
                         open(isas_h).read()):
        opts[m.group(2)] = m.group(1)
    return opts


def feature_bits(cpuinfo_h):
    """FEATURE_X -> list of (leaf, sub, reg, bit_name), from get_available_features."""
    text = open(cpuinfo_h).read()
    # the definition starts at the beginning of a line (GNU style)
    start = re.search(r"^get_available_features\b", text, re.M).start()
    leaf, sub = 1, 0
    found, pending = {}, None
    for line in text[start:].splitlines():
        call = re.search(r"__cpuid_count\s*\(\s*(0x[0-9a-fA-F]+|\d+)\s*,\s*(0x[0-9a-fA-F]+|\d+)", line)
        call1 = re.search(r"__cpuid\s*\(\s*(0x[0-9a-fA-F]+|\d+)\s*,", line)
        if call:
            leaf, sub = int(call.group(1), 0), int(call.group(2), 0)
        elif call1:
            leaf, sub = int(call1.group(1), 0), 0
        test = re.search(r"\bif\s*\(\s*(eax|ebx|ecx|edx)\s*&\s*(bit_\w+)\s*\)", line)
        if test:
            pending = (leaf, sub, test.group(1), test.group(2))
        setf = re.search(r"set_feature\s*\(\s*(FEATURE_\w+)", line)
        if setf and pending:
            found.setdefault(setf.group(1), []).append(pending)
            pending = None
        elif not test and line.strip() and not setf:
            pending = None
        if line.startswith("}"):
            break
    return found


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("gcc_src")
    ap.add_argument("reference")
    ap.add_argument("--signature", help="leaf 1 and 0x80000001 EAX, e.g. 0x00A10F11")
    ap.add_argument("--vendor", choices=["GenuineIntel", "AuthenticAMD"])
    a = ap.parse_args()
    masks = bit_masks(os.path.join(a.gcc_src, "cpuid.h"))
    opts = option_features(os.path.join(a.gcc_src, "i386-isas.h"))
    bits = feature_bits(os.path.join(a.gcc_src, "cpuinfo.h"))
    clear, unmapped = {}, []
    for tok in open(a.reference):
        tok = tok.strip()
        if not tok.startswith("-mno-"):
            continue
        feat = opts.get("-m" + tok[5:])
        where = bits.get(feat, []) if feat else []
        if not where:
            unmapped.append(tok)
            continue
        for leaf, sub, reg, bname in where:
            key = (leaf, sub, REGS[reg])
            clear.setdefault(key, [0, []])
            clear[key][0] |= masks[bname]
            clear[key][1].append(tok[5:])
    print(f"# generated by gen_profile.py from {os.path.basename(a.reference)}")
    if a.vendor:
        v = a.vendor.encode()
        for reg, chunk in ((1, v[0:4]), (3, v[4:8]), (2, v[8:12])):
            print(f"replace 0x0 0 {reg} {int.from_bytes(chunk, 'little'):#010x}")
    intel = a.vendor == "GenuineIntel"
    if intel:
        # Intel leaves the extended vendor string and signature empty
        for reg in (1, 2, 3):
            print(f"replace 0x80000000 0 {reg} 0x00000000")
        print("replace 0x80000001 0 0 0x00000000")
    if a.signature:
        print(f"replace 0x1 0 0 {a.signature}")
        if not intel:
            print(f"replace 0x80000001 0 0 {a.signature}")
    for (leaf, sub, reg), (mask, names) in sorted(clear.items()):
        print(f"clear {leaf:#x} {sub} {reg} {mask:#010x}  # {' '.join(sorted(set(names)))}")
    print(f"# no CPUID bit for: {' '.join(unmapped) if unmapped else '(none)'}")


if __name__ == "__main__":
    sys.exit(main())
