#!/bin/bash
#
# Generate the cpuidmask profile of each CPU target in targets.txt from the
# target's GCC reference in scripts/native_flags/references.
#
# Every -mno-X in the reference becomes a CPUID bit to clear, found through
# GCC's own tables (see gen_profile.py), so the profile hides exactly what the
# reference says the target lacks. The GCC headers are downloaded from the
# gcc-mirror repository for the GCC version given.
#
# usage: generate_profiles.sh [GCC_VERSION]   (default 14.3.0)

set -euo pipefail

SCRIPT_DIR=$(dirname $(realpath ${BASH_SOURCE[0]}))
TOPDIR=$(realpath ${SCRIPT_DIR}/../..)
REFERENCE_DIR=${EESSI_NATIVE_FLAGS_REFERENCE_DIR:-${TOPDIR}/scripts/native_flags/references}
gcc_version=${1:-14.3.0}

headers=$(mktemp -d)
trap 'rm -rf ${headers}' EXIT
url=https://raw.githubusercontent.com/gcc-mirror/gcc/releases/gcc-${gcc_version}/gcc
for f in config/i386/cpuid.h common/config/i386/i386-isas.h common/config/i386/cpuinfo.h; do
    curl -sfL -o ${headers}/$(basename ${f}) ${url}/${f}
done

grep -v '^#' ${SCRIPT_DIR}/targets.txt | while read -r subdir vendor signature rest; do
    [[ -z "${subdir}" ]] && continue
    reference=${REFERENCE_DIR}/${subdir}/gcc-${gcc_version}.txt
    if [[ ! -f "${reference}" ]]; then
        echo ">> No GCC ${gcc_version} reference for ${subdir}, skipping it" >&2
        continue
    fi
    profile=${SCRIPT_DIR}/profiles/${subdir}.rules
    mkdir -p $(dirname ${profile})
    python3 ${SCRIPT_DIR}/gen_profile.py ${headers} ${reference} --vendor ${vendor} --signature ${signature} \
        | sed "1s|.*|# generated by generate_profiles.sh from ${subdir}/gcc-${gcc_version}.txt|" > ${profile}
    echo ">> Wrote ${profile}"
done
